### ISSUE TITLE
add description to available APIs

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-apis#1]
Currently, all the links to various API docs have no description. I think it'll be nice for us to have a description for each API so that anyone who comes across this repository knows what they need to choose, by just reading the description of the org's API.

An example can be see [here](https://github.com/kaf-lamed-beyt/ng-apis#i) &mdash; **Indicina's Decide API**

Here's an approach that I'd suggest you take. You can just try clicking on the link of each API, most of which would take you to the developer docs site, then you can grab the description of such APIs from there, come back, edit the README file, commit your changes, push them, create a Pull Request, and wait for it to be merged. I hope this helps! 

Nonetheless, if you have any questions, please feel free to reach out.

**Comment by DeveloperAspire** [comment]
Hey man! What is going on? Can we discuss more about this? I would love to pick it up.

**Comment by DeveloperAspire** [comment]
I would love to work on this! Let me know if I have a go ahead

**Comment by kaf-lamed-beyt** [comment]
Hi @DeveloperAspire, 

Thank you so much for taking interest in this, and my apologies for the bot's interruption! 😃

**Comment by kaf-lamed-beyt** [comment]
[THIS IS A TEST COMMENT]

Hey, bot!

**Comment by kaf-lamed-beyt** [comment]
Great! bot works as it should!

**Comment by kaf-lamed-beyt** [comment]
So uhm...

@DeveloperAspire, what this issue requires is a description for all the APIs we have in this repo. You can take a look at the way I did it for the Indicina API. So all you'd need to do is, replicate the same thing for all the API links, with their own appropriate descriptions, so that developers can have an idea of what each API is for, before even clicking the links &mdash; saving them the trouble of navigating to each API doc.

**Comment by DeveloperAspire** [comment]
@kaf-lamed-beyt Alrighty, I will start working on it, I will make a PR as soon as I am done.  Cheers!

**Comment by kaf-lamed-beyt** [comment]
Thank you so much, Chief!

**Comment by DeveloperAspire** [comment]
@kaf-lamed-beyt  Some of the APIs are stale and their website shows a 404 or is simply can't be reached. Example the CBN API. What should we do in this case? 

PS: I am 80% done with this Issu

**Comment by kaf-lamed-beyt** [comment]
For the stale APIs... is there a way we can just have their description as is? So perhaps, in the future when there's an update, anyone can add them. You can take this up, if you don't mind.

About the 404 page that the CBN API returns; can you open an issue, for anyone to take on? The issue should probably describe what needs to be done... for example now, you can say "update the CBN API doc link to a correct one"; anything is fine though! 😃


And thanks for the work so far, man!!  I appreciate it.

**Comment by DeveloperAspire** [comment]
I have opened the issue.

**Comment by kaf-lamed-beyt** [comment]
Great! I'll assign you to it now.

**Comment by DeveloperAspire** [comment]
@kaf-lamed-beyt I have completed the task relating to this issue: https://github.com/kaf-lamed-beyt/ng-apis/pull/5

Also please check I have created more issues.

**Comment by kaf-lamed-beyt** [comment]
#5 fixes this issue
